// SPDX-License-Identifier: BSD-3-Clause

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// source: control_v2.proto

package controlv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectType int32

const (
	ObjectType_OBJECT_TYPE_UNSPECIFIED ObjectType = 0
	ObjectType_PORT                    ObjectType = 1
	ObjectType_MODULE                  ObjectType = 2
	ObjectType_CONNECTION              ObjectType = 3
	ObjectType_WORKER                  ObjectType = 4
	ObjectType_TRAFFIC_CLASS           ObjectType = 5
)

// Enum value maps for ObjectType.
var (
	ObjectType_name = map[int32]string{
		0: "OBJECT_TYPE_UNSPECIFIED",
		1: "PORT",
		2: "MODULE",
		3: "CONNECTION",
		4: "WORKER",
		5: "TRAFFIC_CLASS",
	}
	ObjectType_value = map[string]int32{
		"OBJECT_TYPE_UNSPECIFIED": 0,
		"PORT":                    1,
		"MODULE":                  2,
		"CONNECTION":              3,
		"WORKER":                  4,
		"TRAFFIC_CLASS":           5,
	}
)

func (x ObjectType) Enum() *ObjectType {
	p := new(ObjectType)
	*p = x
	return p
}

func (x ObjectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectType) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v2_proto_enumTypes[0].Descriptor()
}

func (ObjectType) Type() protoreflect.EnumType {
	return &file_control_v2_proto_enumTypes[0]
}

func (x ObjectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectType.Descriptor instead.
func (ObjectType) EnumDescriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{0}
}

type ChangeKind int32

const (
	ChangeKind_CHANGE_KIND_UNSPECIFIED ChangeKind = 0
	ChangeKind_CREATE                  ChangeKind = 1
	ChangeKind_REMOVE                  ChangeKind = 2
	ChangeKind_REPLACE                 ChangeKind = 3 // cannot change in place: rebuilt
	ChangeKind_UPDATE                  ChangeKind = 4 // reattached (traffic class parent/priority/share)
	ChangeKind_UPDATE_PARAMS           ChangeKind = 5 // parameters changed in place
)

// Enum value maps for ChangeKind.
var (
	ChangeKind_name = map[int32]string{
		0: "CHANGE_KIND_UNSPECIFIED",
		1: "CREATE",
		2: "REMOVE",
		3: "REPLACE",
		4: "UPDATE",
		5: "UPDATE_PARAMS",
	}
	ChangeKind_value = map[string]int32{
		"CHANGE_KIND_UNSPECIFIED": 0,
		"CREATE":                  1,
		"REMOVE":                  2,
		"REPLACE":                 3,
		"UPDATE":                  4,
		"UPDATE_PARAMS":           5,
	}
)

func (x ChangeKind) Enum() *ChangeKind {
	p := new(ChangeKind)
	*p = x
	return p
}

func (x ChangeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v2_proto_enumTypes[1].Descriptor()
}

func (ChangeKind) Type() protoreflect.EnumType {
	return &file_control_v2_proto_enumTypes[1]
}

func (x ChangeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeKind.Descriptor instead.
func (ChangeKind) EnumDescriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{1}
}

type PlanPhase int32

const (
	PlanPhase_PLAN_PHASE_UNSPECIFIED PlanPhase = 0
	PlanPhase_PREPARE                PlanPhase = 1 // side effects that need no pause and are undoable
	PlanPhase_COMMIT                 PlanPhase = 2 // the switch-over (may pause workers)
	PlanPhase_RETIRE                 PlanPhase = 3 // teardown of what was replaced, after the commit
)

// Enum value maps for PlanPhase.
var (
	PlanPhase_name = map[int32]string{
		0: "PLAN_PHASE_UNSPECIFIED",
		1: "PREPARE",
		2: "COMMIT",
		3: "RETIRE",
	}
	PlanPhase_value = map[string]int32{
		"PLAN_PHASE_UNSPECIFIED": 0,
		"PREPARE":                1,
		"COMMIT":                 2,
		"RETIRE":                 3,
	}
)

func (x PlanPhase) Enum() *PlanPhase {
	p := new(PlanPhase)
	*p = x
	return p
}

func (x PlanPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v2_proto_enumTypes[2].Descriptor()
}

func (PlanPhase) Type() protoreflect.EnumType {
	return &file_control_v2_proto_enumTypes[2]
}

func (x PlanPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanPhase.Descriptor instead.
func (PlanPhase) EnumDescriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{2}
}

type ErrorDetail_Code int32

const (
	ErrorDetail_CODE_UNSPECIFIED        ErrorDetail_Code = 0
	ErrorDetail_INVALID_ARGUMENT        ErrorDetail_Code = 1
	ErrorDetail_NOT_FOUND               ErrorDetail_Code = 2
	ErrorDetail_ALREADY_EXISTS          ErrorDetail_Code = 3
	ErrorDetail_CONFLICT                ErrorDetail_Code = 4
	ErrorDetail_RESOURCE_BUSY           ErrorDetail_Code = 5
	ErrorDetail_UNSUPPORTED_TRANSACTION ErrorDetail_Code = 6
	ErrorDetail_RESOURCE_FAILURE        ErrorDetail_Code = 7
	ErrorDetail_INTERNAL                ErrorDetail_Code = 8
)

// Enum value maps for ErrorDetail_Code.
var (
	ErrorDetail_Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "INVALID_ARGUMENT",
		2: "NOT_FOUND",
		3: "ALREADY_EXISTS",
		4: "CONFLICT",
		5: "RESOURCE_BUSY",
		6: "UNSUPPORTED_TRANSACTION",
		7: "RESOURCE_FAILURE",
		8: "INTERNAL",
	}
	ErrorDetail_Code_value = map[string]int32{
		"CODE_UNSPECIFIED":        0,
		"INVALID_ARGUMENT":        1,
		"NOT_FOUND":               2,
		"ALREADY_EXISTS":          3,
		"CONFLICT":                4,
		"RESOURCE_BUSY":           5,
		"UNSUPPORTED_TRANSACTION": 6,
		"RESOURCE_FAILURE":        7,
		"INTERNAL":                8,
	}
)

func (x ErrorDetail_Code) Enum() *ErrorDetail_Code {
	p := new(ErrorDetail_Code)
	*p = x
	return p
}

func (x ErrorDetail_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorDetail_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v2_proto_enumTypes[3].Descriptor()
}

func (ErrorDetail_Code) Type() protoreflect.EnumType {
	return &file_control_v2_proto_enumTypes[3]
}

func (x ErrorDetail_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorDetail_Code.Descriptor instead.
func (ErrorDetail_Code) EnumDescriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{19, 0}
}

// How the transaction must become visible to packets (M8, D-050). Two
// different promises, never one rounded into the other:
//
//	CONSISTENCY_REFERENTIAL: operations take effect one by one, referents
//	  before referrers; a packet may see part of the transaction applied,
//	  never a reference to something missing. Any resource can take part.
//	CONSISTENCY_SCOPE_SNAPSHOT: every scope the transaction touches
//	  switches from its whole old version to its whole new one in one
//	  store. Only resources that are scope tables can take part; if any
//	  operation names another, the call fails with UNIMPLEMENTED and error
//	  detail UNSUPPORTED_TRANSACTION (field "consistency", object the
//	  resource) and nothing is applied. It is never served as referential.
//
// Unset (UNSPECIFIED) means CONSISTENCY_REFERENTIAL, which is all this
// request could ask before the field existed.
type ApplyTransactionRequest_Consistency int32

const (
	ApplyTransactionRequest_CONSISTENCY_UNSPECIFIED    ApplyTransactionRequest_Consistency = 0
	ApplyTransactionRequest_CONSISTENCY_REFERENTIAL    ApplyTransactionRequest_Consistency = 1
	ApplyTransactionRequest_CONSISTENCY_SCOPE_SNAPSHOT ApplyTransactionRequest_Consistency = 2
)

// Enum value maps for ApplyTransactionRequest_Consistency.
var (
	ApplyTransactionRequest_Consistency_name = map[int32]string{
		0: "CONSISTENCY_UNSPECIFIED",
		1: "CONSISTENCY_REFERENTIAL",
		2: "CONSISTENCY_SCOPE_SNAPSHOT",
	}
	ApplyTransactionRequest_Consistency_value = map[string]int32{
		"CONSISTENCY_UNSPECIFIED":    0,
		"CONSISTENCY_REFERENTIAL":    1,
		"CONSISTENCY_SCOPE_SNAPSHOT": 2,
	}
)

func (x ApplyTransactionRequest_Consistency) Enum() *ApplyTransactionRequest_Consistency {
	p := new(ApplyTransactionRequest_Consistency)
	*p = x
	return p
}

func (x ApplyTransactionRequest_Consistency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplyTransactionRequest_Consistency) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v2_proto_enumTypes[4].Descriptor()
}

func (ApplyTransactionRequest_Consistency) Type() protoreflect.EnumType {
	return &file_control_v2_proto_enumTypes[4]
}

func (x ApplyTransactionRequest_Consistency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplyTransactionRequest_Consistency.Descriptor instead.
func (ApplyTransactionRequest_Consistency) EnumDescriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{21, 0}
}

// Zero is never sent: an unset status must not read as success.
type TransactionOpResult_Status int32

const (
	TransactionOpResult_STATUS_UNSPECIFIED TransactionOpResult_Status = 0
	TransactionOpResult_STATUS_APPLIED     TransactionOpResult_Status = 1
	TransactionOpResult_STATUS_FAILED      TransactionOpResult_Status = 2 // this operation caused the rejection; see error
	TransactionOpResult_STATUS_NOT_APPLIED TransactionOpResult_Status = 3 // the transaction was rejected for another one
)

// Enum value maps for TransactionOpResult_Status.
var (
	TransactionOpResult_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_APPLIED",
		2: "STATUS_FAILED",
		3: "STATUS_NOT_APPLIED",
	}
	TransactionOpResult_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_APPLIED":     1,
		"STATUS_FAILED":      2,
		"STATUS_NOT_APPLIED": 3,
	}
)

func (x TransactionOpResult_Status) Enum() *TransactionOpResult_Status {
	p := new(TransactionOpResult_Status)
	*p = x
	return p
}

func (x TransactionOpResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionOpResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v2_proto_enumTypes[5].Descriptor()
}

func (TransactionOpResult_Status) Type() protoreflect.EnumType {
	return &file_control_v2_proto_enumTypes[5]
}

func (x TransactionOpResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionOpResult_Status.Descriptor instead.
func (TransactionOpResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{22, 0}
}

// Zero is never sent: an unset outcome must not read as applied.
type TransactionRecord_Outcome int32

const (
	TransactionRecord_OUTCOME_UNSPECIFIED TransactionRecord_Outcome = 0
	TransactionRecord_OUTCOME_APPLIED     TransactionRecord_Outcome = 1
	TransactionRecord_OUTCOME_REJECTED    TransactionRecord_Outcome = 2 // an operation failed; nothing changed
	TransactionRecord_OUTCOME_CONFLICT    TransactionRecord_Outcome = 3 // expected_generation did not match; nothing tried
	TransactionRecord_OUTCOME_BUSY        TransactionRecord_Outcome = 4 // readers slow to quiesce; nothing tried, retry
)

// Enum value maps for TransactionRecord_Outcome.
var (
	TransactionRecord_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_APPLIED",
		2: "OUTCOME_REJECTED",
		3: "OUTCOME_CONFLICT",
		4: "OUTCOME_BUSY",
	}
	TransactionRecord_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_APPLIED":     1,
		"OUTCOME_REJECTED":    2,
		"OUTCOME_CONFLICT":    3,
		"OUTCOME_BUSY":        4,
	}
)

func (x TransactionRecord_Outcome) Enum() *TransactionRecord_Outcome {
	p := new(TransactionRecord_Outcome)
	*p = x
	return p
}

func (x TransactionRecord_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionRecord_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v2_proto_enumTypes[6].Descriptor()
}

func (TransactionRecord_Outcome) Type() protoreflect.EnumType {
	return &file_control_v2_proto_enumTypes[6]
}

func (x TransactionRecord_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionRecord_Outcome.Descriptor instead.
func (TransactionRecord_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{23, 0}
}

// The consistency level the transaction ran under (it describes what
// packets could see once the transaction is APPLIED; a transaction that was
// not applied changed nothing):
//
//	VISIBILITY_DEPENDENCY_ORDERED: its operations took effect one by one,
//	  referents before referrers, and no packet saw a reference to
//	  something missing (CONSISTENCY_REFERENTIAL).
//	VISIBILITY_SCOPE_SNAPSHOT: each scope it touched switched from its whole
//	  old version to its whole new one in one store
//	  (CONSISTENCY_SCOPE_SNAPSHOT). There is no order between two scopes.
//
// VISIBILITY_ATOMIC is never sent. It named a promise ("all at once") that
// nothing provides: the strongest guarantee is per scope, and
// VISIBILITY_SCOPE_SNAPSHOT says so. The value stays only because removing
// an enum value breaks `buf breaking`.
type TransactionRecord_Visibility int32

const (
	TransactionRecord_VISIBILITY_UNSPECIFIED        TransactionRecord_Visibility = 0
	TransactionRecord_VISIBILITY_DEPENDENCY_ORDERED TransactionRecord_Visibility = 1
	// Deprecated: Marked as deprecated in control_v2.proto.
	TransactionRecord_VISIBILITY_ATOMIC         TransactionRecord_Visibility = 2
	TransactionRecord_VISIBILITY_SCOPE_SNAPSHOT TransactionRecord_Visibility = 3
)

// Enum value maps for TransactionRecord_Visibility.
var (
	TransactionRecord_Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_DEPENDENCY_ORDERED",
		2: "VISIBILITY_ATOMIC",
		3: "VISIBILITY_SCOPE_SNAPSHOT",
	}
	TransactionRecord_Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED":        0,
		"VISIBILITY_DEPENDENCY_ORDERED": 1,
		"VISIBILITY_ATOMIC":             2,
		"VISIBILITY_SCOPE_SNAPSHOT":     3,
	}
)

func (x TransactionRecord_Visibility) Enum() *TransactionRecord_Visibility {
	p := new(TransactionRecord_Visibility)
	*p = x
	return p
}

func (x TransactionRecord_Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionRecord_Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v2_proto_enumTypes[7].Descriptor()
}

func (TransactionRecord_Visibility) Type() protoreflect.EnumType {
	return &file_control_v2_proto_enumTypes[7]
}

func (x TransactionRecord_Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionRecord_Visibility.Descriptor instead.
func (TransactionRecord_Visibility) EnumDescriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{23, 1}
}

type MetricSample_Kind int32

const (
	MetricSample_KIND_UNSPECIFIED MetricSample_Kind = 0
	MetricSample_KIND_COUNTER     MetricSample_Kind = 1 // monotonic while the daemon runs
	MetricSample_KIND_GAUGE       MetricSample_Kind = 2
)

// Enum value maps for MetricSample_Kind.
var (
	MetricSample_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_COUNTER",
		2: "KIND_GAUGE",
	}
	MetricSample_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_COUNTER":     1,
		"KIND_GAUGE":       2,
	}
)

func (x MetricSample_Kind) Enum() *MetricSample_Kind {
	p := new(MetricSample_Kind)
	*p = x
	return p
}

func (x MetricSample_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricSample_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v2_proto_enumTypes[8].Descriptor()
}

func (MetricSample_Kind) Type() protoreflect.EnumType {
	return &file_control_v2_proto_enumTypes[8]
}

func (x MetricSample_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricSample_Kind.Descriptor instead.
func (MetricSample_Kind) EnumDescriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{31, 0}
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // required: desired state is keyed by stable names
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	NumRxQueues   uint32                 `protobuf:"varint,3,opt,name=num_rx_queues,json=numRxQueues,proto3" json:"num_rx_queues,omitempty"` // 0: one queue
	NumTxQueues   uint32                 `protobuf:"varint,4,opt,name=num_tx_queues,json=numTxQueues,proto3" json:"num_tx_queues,omitempty"`
	RxQueueSize   uint64                 `protobuf:"varint,5,opt,name=rx_queue_size,json=rxQueueSize,proto3" json:"rx_queue_size,omitempty"` // 0: driver default
	TxQueueSize   uint64                 `protobuf:"varint,6,opt,name=tx_queue_size,json=txQueueSize,proto3" json:"tx_queue_size,omitempty"`
	Arg           *anypb.Any             `protobuf:"bytes,7,opt,name=arg,proto3" json:"arg,omitempty"` // driver-specific argument
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_control_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{0}
}

func (x *Port) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Port) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Port) GetNumRxQueues() uint32 {
	if x != nil {
		return x.NumRxQueues
	}
	return 0
}

func (x *Port) GetNumTxQueues() uint32 {
	if x != nil {
		return x.NumTxQueues
	}
	return 0
}

func (x *Port) GetRxQueueSize() uint64 {
	if x != nil {
		return x.RxQueueSize
	}
	return 0
}

func (x *Port) GetTxQueueSize() uint64 {
	if x != nil {
		return x.TxQueueSize
	}
	return 0
}

func (x *Port) GetArg() *anypb.Any {
	if x != nil {
		return x.Arg
	}
	return nil
}

type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mclass        string                 `protobuf:"bytes,2,opt,name=mclass,proto3" json:"mclass,omitempty"`
	Arg           *anypb.Any             `protobuf:"bytes,3,opt,name=arg,proto3" json:"arg,omitempty"` // module Init argument (module_msg.proto)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_control_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{1}
}

func (x *Module) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Module) GetMclass() string {
	if x != nil {
		return x.Mclass
	}
	return ""
}

func (x *Module) GetArg() *anypb.Any {
	if x != nil {
		return x.Arg
	}
	return nil
}

type Connection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Upstream         string                 `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	Ogate            uint32                 `protobuf:"varint,2,opt,name=ogate,proto3" json:"ogate,omitempty"`
	Downstream       string                 `protobuf:"bytes,3,opt,name=downstream,proto3" json:"downstream,omitempty"`
	Igate            uint32                 `protobuf:"varint,4,opt,name=igate,proto3" json:"igate,omitempty"`
	SkipDefaultHooks bool                   `protobuf:"varint,5,opt,name=skip_default_hooks,json=skipDefaultHooks,proto3" json:"skip_default_hooks,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_control_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{2}
}

func (x *Connection) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *Connection) GetOgate() uint32 {
	if x != nil {
		return x.Ogate
	}
	return 0
}

func (x *Connection) GetDownstream() string {
	if x != nil {
		return x.Downstream
	}
	return ""
}

func (x *Connection) GetIgate() uint32 {
	if x != nil {
		return x.Igate
	}
	return 0
}

func (x *Connection) GetSkipDefaultHooks() bool {
	if x != nil {
		return x.SkipDefaultHooks
	}
	return false
}

type Worker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wid           int32                  `protobuf:"varint,1,opt,name=wid,proto3" json:"wid,omitempty"`
	Core          int32                  `protobuf:"varint,2,opt,name=core,proto3" json:"core,omitempty"`
	Scheduler     string                 `protobuf:"bytes,3,opt,name=scheduler,proto3" json:"scheduler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_control_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{3}
}

func (x *Worker) GetWid() int32 {
	if x != nil {
		return x.Wid
	}
	return 0
}

func (x *Worker) GetCore() int32 {
	if x != nil {
		return x.Core
	}
	return 0
}

func (x *Worker) GetScheduler() string {
	if x != nil {
		return x.Scheduler
	}
	return ""
}

type TrafficClass struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parent           string                 `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Policy           string                 `protobuf:"bytes,3,opt,name=policy,proto3" json:"policy,omitempty"`     // "priority", "weighted_fair", "round_robin", "rate_limit", "leaf"
	Resource         string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"` // "count", "cycle", "packet", "bit"
	Wid              int32                  `protobuf:"varint,5,opt,name=wid,proto3" json:"wid,omitempty"`          // -1: any
	Priority         *int64                 `protobuf:"varint,6,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	Share            *int64                 `protobuf:"varint,7,opt,name=share,proto3,oneof" json:"share,omitempty"`
	Limit            map[string]int64       `protobuf:"bytes,8,rep,name=limit,proto3" json:"limit,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MaxBurst         map[string]int64       `protobuf:"bytes,9,rep,name=max_burst,json=maxBurst,proto3" json:"max_burst,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LeafModuleName   string                 `protobuf:"bytes,10,opt,name=leaf_module_name,json=leafModuleName,proto3" json:"leaf_module_name,omitempty"`
	LeafModuleTaskid uint64                 `protobuf:"varint,11,opt,name=leaf_module_taskid,json=leafModuleTaskid,proto3" json:"leaf_module_taskid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrafficClass) Reset() {
	*x = TrafficClass{}
	mi := &file_control_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficClass) ProtoMessage() {}

func (x *TrafficClass) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficClass.ProtoReflect.Descriptor instead.
func (*TrafficClass) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{4}
}

func (x *TrafficClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrafficClass) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *TrafficClass) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *TrafficClass) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *TrafficClass) GetWid() int32 {
	if x != nil {
		return x.Wid
	}
	return 0
}

func (x *TrafficClass) GetPriority() int64 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *TrafficClass) GetShare() int64 {
	if x != nil && x.Share != nil {
		return *x.Share
	}
	return 0
}

func (x *TrafficClass) GetLimit() map[string]int64 {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *TrafficClass) GetMaxBurst() map[string]int64 {
	if x != nil {
		return x.MaxBurst
	}
	return nil
}

func (x *TrafficClass) GetLeafModuleName() string {
	if x != nil {
		return x.LeafModuleName
	}
	return ""
}

func (x *TrafficClass) GetLeafModuleTaskid() uint64 {
	if x != nil {
		return x.LeafModuleTaskid
	}
	return 0
}

type Pipeline struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ports          []*Port                `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	Modules        []*Module              `protobuf:"bytes,2,rep,name=modules,proto3" json:"modules,omitempty"`
	Connections    []*Connection          `protobuf:"bytes,3,rep,name=connections,proto3" json:"connections,omitempty"`
	Workers        []*Worker              `protobuf:"bytes,4,rep,name=workers,proto3" json:"workers,omitempty"`
	TrafficClasses []*TrafficClass        `protobuf:"bytes,5,rep,name=traffic_classes,json=trafficClasses,proto3" json:"traffic_classes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_control_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{5}
}

func (x *Pipeline) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Pipeline) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *Pipeline) GetConnections() []*Connection {
	if x != nil {
		return x.Connections
	}
	return nil
}

func (x *Pipeline) GetWorkers() []*Worker {
	if x != nil {
		return x.Workers
	}
	return nil
}

func (x *Pipeline) GetTrafficClasses() []*TrafficClass {
	if x != nil {
		return x.TrafficClasses
	}
	return nil
}

type Change struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ObjectType             `protobuf:"varint,1,opt,name=type,proto3,enum=bess.pb.v2.ObjectType" json:"type,omitempty"`
	// Object name; for a connection "upstream:ogate->downstream:igate"; for a
	// worker its wid.
	Object        string     `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Kind          ChangeKind `protobuf:"varint,3,opt,name=kind,proto3,enum=bess.pb.v2.ChangeKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_control_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{6}
}

func (x *Change) GetType() ObjectType {
	if x != nil {
		return x.Type
	}
	return ObjectType_OBJECT_TYPE_UNSPECIFIED
}

func (x *Change) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *Change) GetKind() ChangeKind {
	if x != nil {
		return x.Kind
	}
	return ChangeKind_CHANGE_KIND_UNSPECIFIED
}

type PipelineDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*Change              `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"` // unchanged objects are not listed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineDiff) Reset() {
	*x = PipelineDiff{}
	mi := &file_control_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineDiff) ProtoMessage() {}

func (x *PipelineDiff) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineDiff.ProtoReflect.Descriptor instead.
func (*PipelineDiff) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{7}
}

func (x *PipelineDiff) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

type PlanStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         PlanPhase              `protobuf:"varint,1,opt,name=phase,proto3,enum=bess.pb.v2.PlanPhase" json:"phase,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` // e.g. "create_port", "connect", "remove_tc"
	Type          ObjectType             `protobuf:"varint,3,opt,name=type,proto3,enum=bess.pb.v2.ObjectType" json:"type,omitempty"`
	Object        string                 `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanStep) Reset() {
	*x = PlanStep{}
	mi := &file_control_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanStep) ProtoMessage() {}

func (x *PlanStep) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanStep.ProtoReflect.Descriptor instead.
func (*PlanStep) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{8}
}

func (x *PlanStep) GetPhase() PlanPhase {
	if x != nil {
		return x.Phase
	}
	return PlanPhase_PLAN_PHASE_UNSPECIFIED
}

func (x *PlanStep) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *PlanStep) GetType() ObjectType {
	if x != nil {
		return x.Type
	}
	return ObjectType_OBJECT_TYPE_UNSPECIFIED
}

func (x *PlanStep) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type GetPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineRequest) Reset() {
	*x = GetPipelineRequest{}
	mi := &file_control_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineRequest) ProtoMessage() {}

func (x *GetPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineRequest.ProtoReflect.Descriptor instead.
func (*GetPipelineRequest) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{9}
}

type GetPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      *Pipeline              `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"` // the active runtime as desired state
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPipelineResponse) Reset() {
	*x = GetPipelineResponse{}
	mi := &file_control_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPipelineResponse) ProtoMessage() {}

func (x *GetPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPipelineResponse.ProtoReflect.Descriptor instead.
func (*GetPipelineResponse) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{10}
}

func (x *GetPipelineResponse) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *GetPipelineResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type ValidatePipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      *Pipeline              `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePipelineRequest) Reset() {
	*x = ValidatePipelineRequest{}
	mi := &file_control_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePipelineRequest) ProtoMessage() {}

func (x *ValidatePipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePipelineRequest.ProtoReflect.Descriptor instead.
func (*ValidatePipelineRequest) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{11}
}

func (x *ValidatePipelineRequest) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type ValidatePipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Normalized    *Pipeline              `protobuf:"bytes,1,opt,name=normalized,proto3" json:"normalized,omitempty"` // canonical form (stable order, defaults filled)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePipelineResponse) Reset() {
	*x = ValidatePipelineResponse{}
	mi := &file_control_v2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePipelineResponse) ProtoMessage() {}

func (x *ValidatePipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePipelineResponse.ProtoReflect.Descriptor instead.
func (*ValidatePipelineResponse) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{12}
}

func (x *ValidatePipelineResponse) GetNormalized() *Pipeline {
	if x != nil {
		return x.Normalized
	}
	return nil
}

type DiffPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      *Pipeline              `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffPipelineRequest) Reset() {
	*x = DiffPipelineRequest{}
	mi := &file_control_v2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffPipelineRequest) ProtoMessage() {}

func (x *DiffPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffPipelineRequest.ProtoReflect.Descriptor instead.
func (*DiffPipelineRequest) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{13}
}

func (x *DiffPipelineRequest) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type DiffPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          *PipelineDiff          `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"` // the active generation the diff was taken against
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffPipelineResponse) Reset() {
	*x = DiffPipelineResponse{}
	mi := &file_control_v2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffPipelineResponse) ProtoMessage() {}

func (x *DiffPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffPipelineResponse.ProtoReflect.Descriptor instead.
func (*DiffPipelineResponse) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{14}
}

func (x *DiffPipelineResponse) GetDiff() *PipelineDiff {
	if x != nil {
		return x.Diff
	}
	return nil
}

func (x *DiffPipelineResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type PlanPipelineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipeline      *Pipeline              `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanPipelineRequest) Reset() {
	*x = PlanPipelineRequest{}
	mi := &file_control_v2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanPipelineRequest) ProtoMessage() {}

func (x *PlanPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanPipelineRequest.ProtoReflect.Descriptor instead.
func (*PlanPipelineRequest) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{15}
}

func (x *PlanPipelineRequest) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

type PlanPipelineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*PlanStep            `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanPipelineResponse) Reset() {
	*x = PlanPipelineResponse{}
	mi := &file_control_v2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanPipelineResponse) ProtoMessage() {}

func (x *PlanPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanPipelineResponse.ProtoReflect.Descriptor instead.
func (*PlanPipelineResponse) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{16}
}

func (x *PlanPipelineResponse) GetSteps() []*PlanStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *PlanPipelineResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type ApplyPipelineRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Pipeline *Pipeline              `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	// Optimistic concurrency: rejected with ABORTED, before any side effect,
	// if the active generation differs.
	ExpectedGeneration *uint64 `protobuf:"varint,2,opt,name=expected_generation,json=expectedGeneration,proto3,oneof" json:"expected_generation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplyPipelineRequest) Reset() {
	*x = ApplyPipelineRequest{}
	mi := &file_control_v2_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPipelineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPipelineRequest) ProtoMessage() {}

func (x *ApplyPipelineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPipelineRequest.ProtoReflect.Descriptor instead.
func (*ApplyPipelineRequest) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{17}
}

func (x *ApplyPipelineRequest) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *ApplyPipelineRequest) GetExpectedGeneration() uint64 {
	if x != nil && x.ExpectedGeneration != nil {
		return *x.ExpectedGeneration
	}
	return 0
}

type ApplyPipelineResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Generation     uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"` // after the apply (unchanged for a no-op)
	AppliedOps     uint64                 `protobuf:"varint,2,opt,name=applied_ops,json=appliedOps,proto3" json:"applied_ops,omitempty"`
	WorkersPaused  bool                   `protobuf:"varint,3,opt,name=workers_paused,json=workersPaused,proto3" json:"workers_paused,omitempty"`
	ValidationUs   uint64                 `protobuf:"varint,4,opt,name=validation_us,json=validationUs,proto3" json:"validation_us,omitempty"`
	PrepareUs      uint64                 `protobuf:"varint,5,opt,name=prepare_us,json=prepareUs,proto3" json:"prepare_us,omitempty"`
	PausedCommitUs uint64                 `protobuf:"varint,6,opt,name=paused_commit_us,json=pausedCommitUs,proto3" json:"paused_commit_us,omitempty"`
	RetireUs       uint64                 `protobuf:"varint,7,opt,name=retire_us,json=retireUs,proto3" json:"retire_us,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyPipelineResponse) Reset() {
	*x = ApplyPipelineResponse{}
	mi := &file_control_v2_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyPipelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyPipelineResponse) ProtoMessage() {}

func (x *ApplyPipelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyPipelineResponse.ProtoReflect.Descriptor instead.
func (*ApplyPipelineResponse) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{18}
}

func (x *ApplyPipelineResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ApplyPipelineResponse) GetAppliedOps() uint64 {
	if x != nil {
		return x.AppliedOps
	}
	return 0
}

func (x *ApplyPipelineResponse) GetWorkersPaused() bool {
	if x != nil {
		return x.WorkersPaused
	}
	return false
}

func (x *ApplyPipelineResponse) GetValidationUs() uint64 {
	if x != nil {
		return x.ValidationUs
	}
	return 0
}

func (x *ApplyPipelineResponse) GetPrepareUs() uint64 {
	if x != nil {
		return x.PrepareUs
	}
	return 0
}

func (x *ApplyPipelineResponse) GetPausedCommitUs() uint64 {
	if x != nil {
		return x.PausedCommitUs
	}
	return 0
}

func (x *ApplyPipelineResponse) GetRetireUs() uint64 {
	if x != nil {
		return x.RetireUs
	}
	return 0
}

// Carried in the "bess-error-bin" trailer of a failed call.
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorDetail_Code       `protobuf:"varint,1,opt,name=code,proto3,enum=bess.pb.v2.ErrorDetail_Code" json:"code,omitempty"`
	ErrnoValue    int32                  `protobuf:"varint,2,opt,name=errno_value,json=errnoValue,proto3" json:"errno_value,omitempty"` // errno-compatible cause, 0 if none
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Object        string                 `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"` // offending object, when known
	Field         string                 `protobuf:"bytes,5,opt,name=field,proto3" json:"field,omitempty"`   // offending field, when known
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_control_v2_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{19}
}

func (x *ErrorDetail) GetCode() ErrorDetail_Code {
	if x != nil {
		return x.Code
	}
	return ErrorDetail_CODE_UNSPECIFIED
}

func (x *ErrorDetail) GetErrnoValue() int32 {
	if x != nil {
		return x.ErrnoValue
	}
	return 0
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ErrorDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type TransactionOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Erase         bool                   `protobuf:"varint,2,opt,name=erase,proto3" json:"erase,omitempty"` // false: add, or replace if present
	Key           *anypb.Any             `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // not for erase
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionOp) Reset() {
	*x = TransactionOp{}
	mi := &file_control_v2_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionOp) ProtoMessage() {}

func (x *TransactionOp) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionOp.ProtoReflect.Descriptor instead.
func (*TransactionOp) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{20}
}

func (x *TransactionOp) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *TransactionOp) GetErase() bool {
	if x != nil {
		return x.Erase
	}
	return false
}

func (x *TransactionOp) GetKey() *anypb.Any {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *TransactionOp) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type ApplyTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Idempotency (optional but recommended): a repeated request with the
	// same id and contents returns the recorded outcome (replayed = true)
	// instead of applying again; the same id with different contents is
	// refused (ABORTED, error detail CONFLICT). Outcomes are recorded while
	// the daemon runs (a bounded, oldest-first window); use GetTransaction
	// after a timeout.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Refuse (outcome OUTCOME_CONFLICT) unless the dataplane transaction generation
	// is still this.
	ExpectedGeneration *uint64                             `protobuf:"varint,2,opt,name=expected_generation,json=expectedGeneration,proto3,oneof" json:"expected_generation,omitempty"`
	Ops                []*TransactionOp                    `protobuf:"bytes,3,rep,name=ops,proto3" json:"ops,omitempty"`
	Consistency        ApplyTransactionRequest_Consistency `protobuf:"varint,4,opt,name=consistency,proto3,enum=bess.pb.v2.ApplyTransactionRequest_Consistency" json:"consistency,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApplyTransactionRequest) Reset() {
	*x = ApplyTransactionRequest{}
	mi := &file_control_v2_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTransactionRequest) ProtoMessage() {}

func (x *ApplyTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTransactionRequest.ProtoReflect.Descriptor instead.
func (*ApplyTransactionRequest) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{21}
}

func (x *ApplyTransactionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApplyTransactionRequest) GetExpectedGeneration() uint64 {
	if x != nil && x.ExpectedGeneration != nil {
		return *x.ExpectedGeneration
	}
	return 0
}

func (x *ApplyTransactionRequest) GetOps() []*TransactionOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *ApplyTransactionRequest) GetConsistency() ApplyTransactionRequest_Consistency {
	if x != nil {
		return x.Consistency
	}
	return ApplyTransactionRequest_CONSISTENCY_UNSPECIFIED
}

type TransactionOpResult struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        TransactionOpResult_Status `protobuf:"varint,1,opt,name=status,proto3,enum=bess.pb.v2.TransactionOpResult_Status" json:"status,omitempty"`
	Error         string                     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionOpResult) Reset() {
	*x = TransactionOpResult{}
	mi := &file_control_v2_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionOpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionOpResult) ProtoMessage() {}

func (x *TransactionOpResult) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionOpResult.ProtoReflect.Descriptor instead.
func (*TransactionOpResult) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{22}
}

func (x *TransactionOpResult) GetStatus() TransactionOpResult_Status {
	if x != nil {
		return x.Status
	}
	return TransactionOpResult_STATUS_UNSPECIFIED
}

func (x *TransactionOpResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TransactionRecord struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	RequestId     string                       `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Outcome       TransactionRecord_Outcome    `protobuf:"varint,2,opt,name=outcome,proto3,enum=bess.pb.v2.TransactionRecord_Outcome" json:"outcome,omitempty"`
	Generation    uint64                       `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"` // dataplane generation after it
	Ops           []*TransactionOpResult       `protobuf:"bytes,4,rep,name=ops,proto3" json:"ops,omitempty"`                // one per operation, in order
	Visibility    TransactionRecord_Visibility `protobuf:"varint,5,opt,name=visibility,proto3,enum=bess.pb.v2.TransactionRecord_Visibility" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRecord) Reset() {
	*x = TransactionRecord{}
	mi := &file_control_v2_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRecord) ProtoMessage() {}

func (x *TransactionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRecord.ProtoReflect.Descriptor instead.
func (*TransactionRecord) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{23}
}

func (x *TransactionRecord) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TransactionRecord) GetOutcome() TransactionRecord_Outcome {
	if x != nil {
		return x.Outcome
	}
	return TransactionRecord_OUTCOME_UNSPECIFIED
}

func (x *TransactionRecord) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *TransactionRecord) GetOps() []*TransactionOpResult {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *TransactionRecord) GetVisibility() TransactionRecord_Visibility {
	if x != nil {
		return x.Visibility
	}
	return TransactionRecord_VISIBILITY_UNSPECIFIED
}

type ApplyTransactionResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Record *TransactionRecord     `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// Changes when bessd restarts: outcomes recorded under another epoch are
	// gone, so an unknown request_id then means "unknown", not "never ran".
	DaemonEpoch   uint64 `protobuf:"varint,2,opt,name=daemon_epoch,json=daemonEpoch,proto3" json:"daemon_epoch,omitempty"`
	Replayed      bool   `protobuf:"varint,3,opt,name=replayed,proto3" json:"replayed,omitempty"` // the recorded outcome of an earlier identical request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyTransactionResponse) Reset() {
	*x = ApplyTransactionResponse{}
	mi := &file_control_v2_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyTransactionResponse) ProtoMessage() {}

func (x *ApplyTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyTransactionResponse.ProtoReflect.Descriptor instead.
func (*ApplyTransactionResponse) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{24}
}

func (x *ApplyTransactionResponse) GetRecord() *TransactionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ApplyTransactionResponse) GetDaemonEpoch() uint64 {
	if x != nil {
		return x.DaemonEpoch
	}
	return 0
}

func (x *ApplyTransactionResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_control_v2_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{25}
}

func (x *GetTransactionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Known         bool                   `protobuf:"varint,1,opt,name=known,proto3" json:"known,omitempty"` // false: not seen under this epoch, or aged out
	Record        *TransactionRecord     `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	DaemonEpoch   uint64                 `protobuf:"varint,3,opt,name=daemon_epoch,json=daemonEpoch,proto3" json:"daemon_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_control_v2_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{26}
}

func (x *GetTransactionResponse) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

func (x *GetTransactionResponse) GetRecord() *TransactionRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *GetTransactionResponse) GetDaemonEpoch() uint64 {
	if x != nil {
		return x.DaemonEpoch
	}
	return 0
}

type ListTransactionResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionResourcesRequest) Reset() {
	*x = ListTransactionResourcesRequest{}
	mi := &file_control_v2_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionResourcesRequest) ProtoMessage() {}

func (x *ListTransactionResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionResourcesRequest) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{27}
}

type TransactionResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	KeyType       string                 `protobuf:"bytes,2,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`       // protobuf full name of the key message
	ValueType     string                 `protobuf:"bytes,3,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"` // and of the value message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResource) Reset() {
	*x = TransactionResource{}
	mi := &file_control_v2_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResource) ProtoMessage() {}

func (x *TransactionResource) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResource.ProtoReflect.Descriptor instead.
func (*TransactionResource) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{28}
}

func (x *TransactionResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransactionResource) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *TransactionResource) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

type ListTransactionResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*TransactionResource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	DaemonEpoch   uint64                 `protobuf:"varint,3,opt,name=daemon_epoch,json=daemonEpoch,proto3" json:"daemon_epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionResourcesResponse) Reset() {
	*x = ListTransactionResourcesResponse{}
	mi := &file_control_v2_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionResourcesResponse) ProtoMessage() {}

func (x *ListTransactionResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionResourcesResponse) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{29}
}

func (x *ListTransactionResourcesResponse) GetResources() []*TransactionResource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ListTransactionResourcesResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ListTransactionResourcesResponse) GetDaemonEpoch() uint64 {
	if x != nil {
		return x.DaemonEpoch
	}
	return 0
}

type ListMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetricsRequest) Reset() {
	*x = ListMetricsRequest{}
	mi := &file_control_v2_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetricsRequest) ProtoMessage() {}

func (x *ListMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetricsRequest.ProtoReflect.Descriptor instead.
func (*ListMetricsRequest) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{30}
}

type MetricSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          MetricSample_Kind      `protobuf:"varint,2,opt,name=kind,proto3,enum=bess.pb.v2.MetricSample_Kind" json:"kind,omitempty"`
	Help          string                 `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Value         float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_control_v2_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{31}
}

func (x *MetricSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricSample) GetKind() MetricSample_Kind {
	if x != nil {
		return x.Kind
	}
	return MetricSample_KIND_UNSPECIFIED
}

func (x *MetricSample) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *MetricSample) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ListMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*MetricSample        `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`                             // sorted by name, then labels
	DaemonEpoch   uint64                 `protobuf:"varint,2,opt,name=daemon_epoch,json=daemonEpoch,proto3" json:"daemon_epoch,omitempty"` // counters restart with the daemon
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMetricsResponse) Reset() {
	*x = ListMetricsResponse{}
	mi := &file_control_v2_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetricsResponse) ProtoMessage() {}

func (x *ListMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v2_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMetricsResponse.ProtoReflect.Descriptor instead.
func (*ListMetricsResponse) Descriptor() ([]byte, []int) {
	return file_control_v2_proto_rawDescGZIP(), []int{32}
}

func (x *ListMetricsResponse) GetSamples() []*MetricSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *ListMetricsResponse) GetDaemonEpoch() uint64 {
	if x != nil {
		return x.DaemonEpoch
	}
	return 0
}

var File_control_v2_proto protoreflect.FileDescriptor

const file_control_v2_proto_rawDesc = "" +
	"\n" +
	"\x10control_v2.proto\x12\n" +
	"bess.pb.v2\x1a\x19google/protobuf/any.proto\"\xea\x01\n" +
	"\x04Port\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\"\n" +
	"\rnum_rx_queues\x18\x03 \x01(\rR\vnumRxQueues\x12\"\n" +
	"\rnum_tx_queues\x18\x04 \x01(\rR\vnumTxQueues\x12\"\n" +
	"\rrx_queue_size\x18\x05 \x01(\x04R\vrxQueueSize\x12\"\n" +
	"\rtx_queue_size\x18\x06 \x01(\x04R\vtxQueueSize\x12&\n" +
	"\x03arg\x18\a \x01(\v2\x14.google.protobuf.AnyR\x03arg\"\\\n" +
	"\x06Module\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06mclass\x18\x02 \x01(\tR\x06mclass\x12&\n" +
	"\x03arg\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x03arg\"\xa2\x01\n" +
	"\n" +
	"Connection\x12\x1a\n" +
	"\bupstream\x18\x01 \x01(\tR\bupstream\x12\x14\n" +
	"\x05ogate\x18\x02 \x01(\rR\x05ogate\x12\x1e\n" +
	"\n" +
	"downstream\x18\x03 \x01(\tR\n" +
	"downstream\x12\x14\n" +
	"\x05igate\x18\x04 \x01(\rR\x05igate\x12,\n" +
	"\x12skip_default_hooks\x18\x05 \x01(\bR\x10skipDefaultHooks\"L\n" +
	"\x06Worker\x12\x10\n" +
	"\x03wid\x18\x01 \x01(\x05R\x03wid\x12\x12\n" +
	"\x04core\x18\x02 \x01(\x05R\x04core\x12\x1c\n" +
	"\tscheduler\x18\x03 \x01(\tR\tscheduler\"\xa2\x04\n" +
	"\fTrafficClass\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\tR\x06parent\x12\x16\n" +
	"\x06policy\x18\x03 \x01(\tR\x06policy\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x10\n" +
	"\x03wid\x18\x05 \x01(\x05R\x03wid\x12\x1f\n" +
	"\bpriority\x18\x06 \x01(\x03H\x00R\bpriority\x88\x01\x01\x12\x19\n" +
	"\x05share\x18\a \x01(\x03H\x01R\x05share\x88\x01\x01\x129\n" +
	"\x05limit\x18\b \x03(\v2#.bess.pb.v2.TrafficClass.LimitEntryR\x05limit\x12C\n" +
	"\tmax_burst\x18\t \x03(\v2&.bess.pb.v2.TrafficClass.MaxBurstEntryR\bmaxBurst\x12(\n" +
	"\x10leaf_module_name\x18\n" +
	" \x01(\tR\x0eleafModuleName\x12,\n" +
	"\x12leaf_module_taskid\x18\v \x01(\x04R\x10leafModuleTaskid\x1a8\n" +
	"\n" +
	"LimitEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a;\n" +
	"\rMaxBurstEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B\v\n" +
	"\t_priorityB\b\n" +
	"\x06_share\"\x8b\x02\n" +
	"\bPipeline\x12&\n" +
	"\x05ports\x18\x01 \x03(\v2\x10.bess.pb.v2.PortR\x05ports\x12,\n" +
	"\amodules\x18\x02 \x03(\v2\x12.bess.pb.v2.ModuleR\amodules\x128\n" +
	"\vconnections\x18\x03 \x03(\v2\x16.bess.pb.v2.ConnectionR\vconnections\x12,\n" +
	"\aworkers\x18\x04 \x03(\v2\x12.bess.pb.v2.WorkerR\aworkers\x12A\n" +
	"\x0ftraffic_classes\x18\x05 \x03(\v2\x18.bess.pb.v2.TrafficClassR\x0etrafficClasses\"x\n" +
	"\x06Change\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.bess.pb.v2.ObjectTypeR\x04type\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12*\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x16.bess.pb.v2.ChangeKindR\x04kind\"<\n" +
	"\fPipelineDiff\x12,\n" +
	"\achanges\x18\x01 \x03(\v2\x12.bess.pb.v2.ChangeR\achanges\"\x99\x01\n" +
	"\bPlanStep\x12+\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x15.bess.pb.v2.PlanPhaseR\x05phase\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.bess.pb.v2.ObjectTypeR\x04type\x12\x16\n" +
	"\x06object\x18\x04 \x01(\tR\x06object\"\x14\n" +
	"\x12GetPipelineRequest\"g\n" +
	"\x13GetPipelineResponse\x120\n" +
	"\bpipeline\x18\x01 \x01(\v2\x14.bess.pb.v2.PipelineR\bpipeline\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\"K\n" +
	"\x17ValidatePipelineRequest\x120\n" +
	"\bpipeline\x18\x01 \x01(\v2\x14.bess.pb.v2.PipelineR\bpipeline\"P\n" +
	"\x18ValidatePipelineResponse\x124\n" +
	"\n" +
	"normalized\x18\x01 \x01(\v2\x14.bess.pb.v2.PipelineR\n" +
	"normalized\"G\n" +
	"\x13DiffPipelineRequest\x120\n" +
	"\bpipeline\x18\x01 \x01(\v2\x14.bess.pb.v2.PipelineR\bpipeline\"d\n" +
	"\x14DiffPipelineResponse\x12,\n" +
	"\x04diff\x18\x01 \x01(\v2\x18.bess.pb.v2.PipelineDiffR\x04diff\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\"G\n" +
	"\x13PlanPipelineRequest\x120\n" +
	"\bpipeline\x18\x01 \x01(\v2\x14.bess.pb.v2.PipelineR\bpipeline\"b\n" +
	"\x14PlanPipelineResponse\x12*\n" +
	"\x05steps\x18\x01 \x03(\v2\x14.bess.pb.v2.PlanStepR\x05steps\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\"\x96\x01\n" +
	"\x14ApplyPipelineRequest\x120\n" +
	"\bpipeline\x18\x01 \x01(\v2\x14.bess.pb.v2.PipelineR\bpipeline\x124\n" +
	"\x13expected_generation\x18\x02 \x01(\x04H\x00R\x12expectedGeneration\x88\x01\x01B\x16\n" +
	"\x14_expected_generation\"\x8a\x02\n" +
	"\x15ApplyPipelineResponse\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12\x1f\n" +
	"\vapplied_ops\x18\x02 \x01(\x04R\n" +
	"appliedOps\x12%\n" +
	"\x0eworkers_paused\x18\x03 \x01(\bR\rworkersPaused\x12#\n" +
	"\rvalidation_us\x18\x04 \x01(\x04R\fvalidationUs\x12\x1d\n" +
	"\n" +
	"prepare_us\x18\x05 \x01(\x04R\tprepareUs\x12(\n" +
	"\x10paused_commit_us\x18\x06 \x01(\x04R\x0epausedCommitUs\x12\x1b\n" +
	"\tretire_us\x18\a \x01(\x04R\bretireUs\"\xe2\x02\n" +
	"\vErrorDetail\x120\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1c.bess.pb.v2.ErrorDetail.CodeR\x04code\x12\x1f\n" +
	"\verrno_value\x18\x02 \x01(\x05R\n" +
	"errnoValue\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06object\x18\x04 \x01(\tR\x06object\x12\x14\n" +
	"\x05field\x18\x05 \x01(\tR\x05field\"\xb7\x01\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x03\x12\f\n" +
	"\bCONFLICT\x10\x04\x12\x11\n" +
	"\rRESOURCE_BUSY\x10\x05\x12\x1b\n" +
	"\x17UNSUPPORTED_TRANSACTION\x10\x06\x12\x14\n" +
	"\x10RESOURCE_FAILURE\x10\a\x12\f\n" +
	"\bINTERNAL\x10\b\"\x95\x01\n" +
	"\rTransactionOp\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x14\n" +
	"\x05erase\x18\x02 \x01(\bR\x05erase\x12&\n" +
	"\x03key\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x03key\x12*\n" +
	"\x05value\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x05value\"\xef\x02\n" +
	"\x17ApplyTransactionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x124\n" +
	"\x13expected_generation\x18\x02 \x01(\x04H\x00R\x12expectedGeneration\x88\x01\x01\x12+\n" +
	"\x03ops\x18\x03 \x03(\v2\x19.bess.pb.v2.TransactionOpR\x03ops\x12Q\n" +
	"\vconsistency\x18\x04 \x01(\x0e2/.bess.pb.v2.ApplyTransactionRequest.ConsistencyR\vconsistency\"g\n" +
	"\vConsistency\x12\x1b\n" +
	"\x17CONSISTENCY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONSISTENCY_REFERENTIAL\x10\x01\x12\x1e\n" +
	"\x1aCONSISTENCY_SCOPE_SNAPSHOT\x10\x02B\x16\n" +
	"\x14_expected_generation\"\xcc\x01\n" +
	"\x13TransactionOpResult\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.bess.pb.v2.TransactionOpResult.StatusR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"_\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_APPLIED\x10\x01\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x02\x12\x16\n" +
	"\x12STATUS_NOT_APPLIED\x10\x03\"\x8f\x04\n" +
	"\x11TransactionRecord\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12?\n" +
	"\aoutcome\x18\x02 \x01(\x0e2%.bess.pb.v2.TransactionRecord.OutcomeR\aoutcome\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\x121\n" +
	"\x03ops\x18\x04 \x03(\v2\x1f.bess.pb.v2.TransactionOpResultR\x03ops\x12H\n" +
	"\n" +
	"visibility\x18\x05 \x01(\x0e2(.bess.pb.v2.TransactionRecord.VisibilityR\n" +
	"visibility\"u\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOUTCOME_APPLIED\x10\x01\x12\x14\n" +
	"\x10OUTCOME_REJECTED\x10\x02\x12\x14\n" +
	"\x10OUTCOME_CONFLICT\x10\x03\x12\x10\n" +
	"\fOUTCOME_BUSY\x10\x04\"\x85\x01\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dVISIBILITY_DEPENDENCY_ORDERED\x10\x01\x12\x19\n" +
	"\x11VISIBILITY_ATOMIC\x10\x02\x1a\x02\b\x01\x12\x1d\n" +
	"\x19VISIBILITY_SCOPE_SNAPSHOT\x10\x03\"\x90\x01\n" +
	"\x18ApplyTransactionResponse\x125\n" +
	"\x06record\x18\x01 \x01(\v2\x1d.bess.pb.v2.TransactionRecordR\x06record\x12!\n" +
	"\fdaemon_epoch\x18\x02 \x01(\x04R\vdaemonEpoch\x12\x1a\n" +
	"\breplayed\x18\x03 \x01(\bR\breplayed\"6\n" +
	"\x15GetTransactionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"\x88\x01\n" +
	"\x16GetTransactionResponse\x12\x14\n" +
	"\x05known\x18\x01 \x01(\bR\x05known\x125\n" +
	"\x06record\x18\x02 \x01(\v2\x1d.bess.pb.v2.TransactionRecordR\x06record\x12!\n" +
	"\fdaemon_epoch\x18\x03 \x01(\x04R\vdaemonEpoch\"!\n" +
	"\x1fListTransactionResourcesRequest\"c\n" +
	"\x13TransactionResource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bkey_type\x18\x02 \x01(\tR\akeyType\x12\x1d\n" +
	"\n" +
	"value_type\x18\x03 \x01(\tR\tvalueType\"\xa4\x01\n" +
	" ListTransactionResourcesResponse\x12=\n" +
	"\tresources\x18\x01 \x03(\v2\x1f.bess.pb.v2.TransactionResourceR\tresources\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12!\n" +
	"\fdaemon_epoch\x18\x03 \x01(\x04R\vdaemonEpoch\"\x14\n" +
	"\x12ListMetricsRequest\"\xb8\x02\n" +
	"\fMetricSample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1d.bess.pb.v2.MetricSample.KindR\x04kind\x12\x12\n" +
	"\x04help\x18\x03 \x01(\tR\x04help\x12<\n" +
	"\x06labels\x18\x04 \x03(\v2$.bess.pb.v2.MetricSample.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fKIND_COUNTER\x10\x01\x12\x0e\n" +
	"\n" +
	"KIND_GAUGE\x10\x02\"l\n" +
	"\x13ListMetricsResponse\x122\n" +
	"\asamples\x18\x01 \x03(\v2\x18.bess.pb.v2.MetricSampleR\asamples\x12!\n" +
	"\fdaemon_epoch\x18\x02 \x01(\x04R\vdaemonEpoch*n\n" +
	"\n" +
	"ObjectType\x12\x1b\n" +
	"\x17OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04PORT\x10\x01\x12\n" +
	"\n" +
	"\x06MODULE\x10\x02\x12\x0e\n" +
	"\n" +
	"CONNECTION\x10\x03\x12\n" +
	"\n" +
	"\x06WORKER\x10\x04\x12\x11\n" +
	"\rTRAFFIC_CLASS\x10\x05*m\n" +
	"\n" +
	"ChangeKind\x12\x1b\n" +
	"\x17CHANGE_KIND_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x02\x12\v\n" +
	"\aREPLACE\x10\x03\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x04\x12\x11\n" +
	"\rUPDATE_PARAMS\x10\x05*L\n" +
	"\tPlanPhase\x12\x1a\n" +
	"\x16PLAN_PHASE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPREPARE\x10\x01\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x02\x12\n" +
	"\n" +
	"\x06RETIRE\x10\x032\xc5\x06\n" +
	"\aControl\x12P\n" +
	"\vGetPipeline\x12\x1e.bess.pb.v2.GetPipelineRequest\x1a\x1f.bess.pb.v2.GetPipelineResponse\"\x00\x12_\n" +
	"\x10ValidatePipeline\x12#.bess.pb.v2.ValidatePipelineRequest\x1a$.bess.pb.v2.ValidatePipelineResponse\"\x00\x12S\n" +
	"\fDiffPipeline\x12\x1f.bess.pb.v2.DiffPipelineRequest\x1a .bess.pb.v2.DiffPipelineResponse\"\x00\x12S\n" +
	"\fPlanPipeline\x12\x1f.bess.pb.v2.PlanPipelineRequest\x1a .bess.pb.v2.PlanPipelineResponse\"\x00\x12V\n" +
	"\rApplyPipeline\x12 .bess.pb.v2.ApplyPipelineRequest\x1a!.bess.pb.v2.ApplyPipelineResponse\"\x00\x12_\n" +
	"\x10ApplyTransaction\x12#.bess.pb.v2.ApplyTransactionRequest\x1a$.bess.pb.v2.ApplyTransactionResponse\"\x00\x12Y\n" +
	"\x0eGetTransaction\x12!.bess.pb.v2.GetTransactionRequest\x1a\".bess.pb.v2.GetTransactionResponse\"\x00\x12P\n" +
	"\vListMetrics\x12\x1e.bess.pb.v2.ListMetricsRequest\x1a\x1f.bess.pb.v2.ListMetricsResponse\"\x00\x12w\n" +
	"\x18ListTransactionResources\x12+.bess.pb.v2.ListTransactionResourcesRequest\x1a,.bess.pb.v2.ListTransactionResourcesResponse\"\x00b\x06proto3"

var (
	file_control_v2_proto_rawDescOnce sync.Once
	file_control_v2_proto_rawDescData []byte
)

func file_control_v2_proto_rawDescGZIP() []byte {
	file_control_v2_proto_rawDescOnce.Do(func() {
		file_control_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_v2_proto_rawDesc), len(file_control_v2_proto_rawDesc)))
	})
	return file_control_v2_proto_rawDescData
}

var file_control_v2_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_control_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_control_v2_proto_goTypes = []any{
	(ObjectType)(0),                          // 0: bess.pb.v2.ObjectType
	(ChangeKind)(0),                          // 1: bess.pb.v2.ChangeKind
	(PlanPhase)(0),                           // 2: bess.pb.v2.PlanPhase
	(ErrorDetail_Code)(0),                    // 3: bess.pb.v2.ErrorDetail.Code
	(ApplyTransactionRequest_Consistency)(0), // 4: bess.pb.v2.ApplyTransactionRequest.Consistency
	(TransactionOpResult_Status)(0),          // 5: bess.pb.v2.TransactionOpResult.Status
	(TransactionRecord_Outcome)(0),           // 6: bess.pb.v2.TransactionRecord.Outcome
	(TransactionRecord_Visibility)(0),        // 7: bess.pb.v2.TransactionRecord.Visibility
	(MetricSample_Kind)(0),                   // 8: bess.pb.v2.MetricSample.Kind
	(*Port)(nil),                             // 9: bess.pb.v2.Port
	(*Module)(nil),                           // 10: bess.pb.v2.Module
	(*Connection)(nil),                       // 11: bess.pb.v2.Connection
	(*Worker)(nil),                           // 12: bess.pb.v2.Worker
	(*TrafficClass)(nil),                     // 13: bess.pb.v2.TrafficClass
	(*Pipeline)(nil),                         // 14: bess.pb.v2.Pipeline
	(*Change)(nil),                           // 15: bess.pb.v2.Change
	(*PipelineDiff)(nil),                     // 16: bess.pb.v2.PipelineDiff
	(*PlanStep)(nil),                         // 17: bess.pb.v2.PlanStep
	(*GetPipelineRequest)(nil),               // 18: bess.pb.v2.GetPipelineRequest
	(*GetPipelineResponse)(nil),              // 19: bess.pb.v2.GetPipelineResponse
	(*ValidatePipelineRequest)(nil),          // 20: bess.pb.v2.ValidatePipelineRequest
	(*ValidatePipelineResponse)(nil),         // 21: bess.pb.v2.ValidatePipelineResponse
	(*DiffPipelineRequest)(nil),              // 22: bess.pb.v2.DiffPipelineRequest
	(*DiffPipelineResponse)(nil),             // 23: bess.pb.v2.DiffPipelineResponse
	(*PlanPipelineRequest)(nil),              // 24: bess.pb.v2.PlanPipelineRequest
	(*PlanPipelineResponse)(nil),             // 25: bess.pb.v2.PlanPipelineResponse
	(*ApplyPipelineRequest)(nil),             // 26: bess.pb.v2.ApplyPipelineRequest
	(*ApplyPipelineResponse)(nil),            // 27: bess.pb.v2.ApplyPipelineResponse
	(*ErrorDetail)(nil),                      // 28: bess.pb.v2.ErrorDetail
	(*TransactionOp)(nil),                    // 29: bess.pb.v2.TransactionOp
	(*ApplyTransactionRequest)(nil),          // 30: bess.pb.v2.ApplyTransactionRequest
	(*TransactionOpResult)(nil),              // 31: bess.pb.v2.TransactionOpResult
	(*TransactionRecord)(nil),                // 32: bess.pb.v2.TransactionRecord
	(*ApplyTransactionResponse)(nil),         // 33: bess.pb.v2.ApplyTransactionResponse
	(*GetTransactionRequest)(nil),            // 34: bess.pb.v2.GetTransactionRequest
	(*GetTransactionResponse)(nil),           // 35: bess.pb.v2.GetTransactionResponse
	(*ListTransactionResourcesRequest)(nil),  // 36: bess.pb.v2.ListTransactionResourcesRequest
	(*TransactionResource)(nil),              // 37: bess.pb.v2.TransactionResource
	(*ListTransactionResourcesResponse)(nil), // 38: bess.pb.v2.ListTransactionResourcesResponse
	(*ListMetricsRequest)(nil),               // 39: bess.pb.v2.ListMetricsRequest
	(*MetricSample)(nil),                     // 40: bess.pb.v2.MetricSample
	(*ListMetricsResponse)(nil),              // 41: bess.pb.v2.ListMetricsResponse
	nil,                                      // 42: bess.pb.v2.TrafficClass.LimitEntry
	nil,                                      // 43: bess.pb.v2.TrafficClass.MaxBurstEntry
	nil,                                      // 44: bess.pb.v2.MetricSample.LabelsEntry
	(*anypb.Any)(nil),                        // 45: google.protobuf.Any
}
var file_control_v2_proto_depIdxs = []int32{
	45, // 0: bess.pb.v2.Port.arg:type_name -> google.protobuf.Any
	45, // 1: bess.pb.v2.Module.arg:type_name -> google.protobuf.Any
	42, // 2: bess.pb.v2.TrafficClass.limit:type_name -> bess.pb.v2.TrafficClass.LimitEntry
	43, // 3: bess.pb.v2.TrafficClass.max_burst:type_name -> bess.pb.v2.TrafficClass.MaxBurstEntry
	9,  // 4: bess.pb.v2.Pipeline.ports:type_name -> bess.pb.v2.Port
	10, // 5: bess.pb.v2.Pipeline.modules:type_name -> bess.pb.v2.Module
	11, // 6: bess.pb.v2.Pipeline.connections:type_name -> bess.pb.v2.Connection
	12, // 7: bess.pb.v2.Pipeline.workers:type_name -> bess.pb.v2.Worker
	13, // 8: bess.pb.v2.Pipeline.traffic_classes:type_name -> bess.pb.v2.TrafficClass
	0,  // 9: bess.pb.v2.Change.type:type_name -> bess.pb.v2.ObjectType
	1,  // 10: bess.pb.v2.Change.kind:type_name -> bess.pb.v2.ChangeKind
	15, // 11: bess.pb.v2.PipelineDiff.changes:type_name -> bess.pb.v2.Change
	2,  // 12: bess.pb.v2.PlanStep.phase:type_name -> bess.pb.v2.PlanPhase
	0,  // 13: bess.pb.v2.PlanStep.type:type_name -> bess.pb.v2.ObjectType
	14, // 14: bess.pb.v2.GetPipelineResponse.pipeline:type_name -> bess.pb.v2.Pipeline
	14, // 15: bess.pb.v2.ValidatePipelineRequest.pipeline:type_name -> bess.pb.v2.Pipeline
	14, // 16: bess.pb.v2.ValidatePipelineResponse.normalized:type_name -> bess.pb.v2.Pipeline
	14, // 17: bess.pb.v2.DiffPipelineRequest.pipeline:type_name -> bess.pb.v2.Pipeline
	16, // 18: bess.pb.v2.DiffPipelineResponse.diff:type_name -> bess.pb.v2.PipelineDiff
	14, // 19: bess.pb.v2.PlanPipelineRequest.pipeline:type_name -> bess.pb.v2.Pipeline
	17, // 20: bess.pb.v2.PlanPipelineResponse.steps:type_name -> bess.pb.v2.PlanStep
	14, // 21: bess.pb.v2.ApplyPipelineRequest.pipeline:type_name -> bess.pb.v2.Pipeline
	3,  // 22: bess.pb.v2.ErrorDetail.code:type_name -> bess.pb.v2.ErrorDetail.Code
	45, // 23: bess.pb.v2.TransactionOp.key:type_name -> google.protobuf.Any
	45, // 24: bess.pb.v2.TransactionOp.value:type_name -> google.protobuf.Any
	29, // 25: bess.pb.v2.ApplyTransactionRequest.ops:type_name -> bess.pb.v2.TransactionOp
	4,  // 26: bess.pb.v2.ApplyTransactionRequest.consistency:type_name -> bess.pb.v2.ApplyTransactionRequest.Consistency
	5,  // 27: bess.pb.v2.TransactionOpResult.status:type_name -> bess.pb.v2.TransactionOpResult.Status
	6,  // 28: bess.pb.v2.TransactionRecord.outcome:type_name -> bess.pb.v2.TransactionRecord.Outcome
	31, // 29: bess.pb.v2.TransactionRecord.ops:type_name -> bess.pb.v2.TransactionOpResult
	7,  // 30: bess.pb.v2.TransactionRecord.visibility:type_name -> bess.pb.v2.TransactionRecord.Visibility
	32, // 31: bess.pb.v2.ApplyTransactionResponse.record:type_name -> bess.pb.v2.TransactionRecord
	32, // 32: bess.pb.v2.GetTransactionResponse.record:type_name -> bess.pb.v2.TransactionRecord
	37, // 33: bess.pb.v2.ListTransactionResourcesResponse.resources:type_name -> bess.pb.v2.TransactionResource
	8,  // 34: bess.pb.v2.MetricSample.kind:type_name -> bess.pb.v2.MetricSample.Kind
	44, // 35: bess.pb.v2.MetricSample.labels:type_name -> bess.pb.v2.MetricSample.LabelsEntry
	40, // 36: bess.pb.v2.ListMetricsResponse.samples:type_name -> bess.pb.v2.MetricSample
	18, // 37: bess.pb.v2.Control.GetPipeline:input_type -> bess.pb.v2.GetPipelineRequest
	20, // 38: bess.pb.v2.Control.ValidatePipeline:input_type -> bess.pb.v2.ValidatePipelineRequest
	22, // 39: bess.pb.v2.Control.DiffPipeline:input_type -> bess.pb.v2.DiffPipelineRequest
	24, // 40: bess.pb.v2.Control.PlanPipeline:input_type -> bess.pb.v2.PlanPipelineRequest
	26, // 41: bess.pb.v2.Control.ApplyPipeline:input_type -> bess.pb.v2.ApplyPipelineRequest
	30, // 42: bess.pb.v2.Control.ApplyTransaction:input_type -> bess.pb.v2.ApplyTransactionRequest
	34, // 43: bess.pb.v2.Control.GetTransaction:input_type -> bess.pb.v2.GetTransactionRequest
	39, // 44: bess.pb.v2.Control.ListMetrics:input_type -> bess.pb.v2.ListMetricsRequest
	36, // 45: bess.pb.v2.Control.ListTransactionResources:input_type -> bess.pb.v2.ListTransactionResourcesRequest
	19, // 46: bess.pb.v2.Control.GetPipeline:output_type -> bess.pb.v2.GetPipelineResponse
	21, // 47: bess.pb.v2.Control.ValidatePipeline:output_type -> bess.pb.v2.ValidatePipelineResponse
	23, // 48: bess.pb.v2.Control.DiffPipeline:output_type -> bess.pb.v2.DiffPipelineResponse
	25, // 49: bess.pb.v2.Control.PlanPipeline:output_type -> bess.pb.v2.PlanPipelineResponse
	27, // 50: bess.pb.v2.Control.ApplyPipeline:output_type -> bess.pb.v2.ApplyPipelineResponse
	33, // 51: bess.pb.v2.Control.ApplyTransaction:output_type -> bess.pb.v2.ApplyTransactionResponse
	35, // 52: bess.pb.v2.Control.GetTransaction:output_type -> bess.pb.v2.GetTransactionResponse
	41, // 53: bess.pb.v2.Control.ListMetrics:output_type -> bess.pb.v2.ListMetricsResponse
	38, // 54: bess.pb.v2.Control.ListTransactionResources:output_type -> bess.pb.v2.ListTransactionResourcesResponse
	46, // [46:55] is the sub-list for method output_type
	37, // [37:46] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_control_v2_proto_init() }
func file_control_v2_proto_init() {
	if File_control_v2_proto != nil {
		return
	}
	file_control_v2_proto_msgTypes[4].OneofWrappers = []any{}
	file_control_v2_proto_msgTypes[17].OneofWrappers = []any{}
	file_control_v2_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_v2_proto_rawDesc), len(file_control_v2_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_v2_proto_goTypes,
		DependencyIndexes: file_control_v2_proto_depIdxs,
		EnumInfos:         file_control_v2_proto_enumTypes,
		MessageInfos:      file_control_v2_proto_msgTypes,
	}.Build()
	File_control_v2_proto = out.File
	file_control_v2_proto_goTypes = nil
	file_control_v2_proto_depIdxs = nil
}
