#!/bin/sh -e

build_dir=${BESS_BUILD_DIR:-../build-meson}
args=${1:-run}

for arg in $args; do
    case $arg in
        run)
            meson test -C "$build_dir" --print-errorlogs
            ;;
        serve)
            coverage_dir="$build_dir/meson-logs"
            echo "Serving Meson logs at http://localhost:8000"
            python3 -m http.server 8000 --directory "$coverage_dir"
            ;;
        *)
            echo "Unknown command '$arg'" >&2
            echo "Usage: $0 [run] [serve]" >&2
            exit 2
            ;;
    esac
done
