#! /usr/bin/env python
# Copyright (c) 2017, Nefeli Networks, Inc.
# SPDX-License-Identifier: BSD-3-Clause

"""
Pseduo-module multi-import.

This code is intended to allow you to write, e.g.:

    foo_names = ['foo.' + path[:-3]
        for path in os.listdir('foo') if path.endswith('.py')]
    modname = pm_import('foo', foo_names)

to import the entire contents of directory "foo" as if it
were all just one big file.
"""

import importlib
import sys
import types

__std_skip = set(n for n in sys.modules[__name__].__dict__.keys()
                 if n.startswith('__'))


class Collisions(Exception):
    def __init__(self, *args, **kwargs):
        self.collisions = kwargs.pop('collisions')
        super(Collisions, self).__init__(*args, **kwargs)


def pm_import(mname, iterator, name_filter=None, package=None, override=False):
    """
    Import all files generated by the iterator, copying some of
    its names into a pseudo-module.

    Note: for this to work on a directory, the directory will
    typically have to contain an __init__.py.  If that is not
    empty you probably should be skipping it.

    You get something much like the effect of running:

    if mname in sys.modules:
        return sys.modules[mname]
    module = types.ModuleType(mname)
    for submodule in iterator:
        tmp = importlib.import_module(submodule, package)
        names = filter(name_filter, tmp.__dict__['__all__'])
        module.__dict__.update(names)
    sys.modules[mname] = module
    return module

    (except a missing __all__ gets names as usual).

    If override is True, this really is nearly all this
    does.  If override is False (the default), this also makes
    sure the names are all unique, and if not, raises a
    Collisions error.

    Note: if name_filter is None, all names pass through it.
    A typical actual filter might be:

        name_filter=lambda name: name.startswith('take_me_')

    which would combine all names starting with 'take_me_', such as
    'take_me_home', 'take_me_later', and so on.
    """
    module = sys.modules.get(mname, None)
    if module is not None:
        return module
    allnames = set()
    collisions = set()
    sources = {}
    module = types.ModuleType(mname)
    for submodule in iterator:
        tmp = importlib.import_module(submodule, package)
        try:
            names = tmp.__dict__['__all__']
        except KeyError:
            # standard names like __name__ will always conflict,
            # so always skip them.
            names = set(tmp.__dict__.keys()) - __std_skip
        names = filter(name_filter, names)
        if not override:
            # make set now, we can't iterate over the filter result twice
            names = set(names)

        # Update return value, assuming lack of collisions
        # or desire to keep last-recorded name.
        module.__dict__.update({ k: tmp.__dict__[k] for k in names })

        if override:
            continue

        # convert names to set for fast collision detection
        #names = set(names) -- done above
        collisions |= names & allnames
        allnames |= names
        for k in names:
            # add this submodule to sources for this name
            sources.setdefault(k, []).append(tmp.__name__)

    # If override is True, collisions() is the empty set.
    # If not, it's the set of name/value pairs we want to
    # *keep* from sources.
    if collisions:
        collisions = { k: sources[k] for k in collisions }
        raise Collisions('non-unique names in pm_import({!r})'.format(mname),
                         collisions=collisions)

    sys.modules[mname] = module
    return module
